version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tech_challenge_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_NAME: tech_challenge_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
